---
# tasks file for myapache
- name: Installing httpd
  package:
     name: httpd
     state: present

- name: Installing php
  package:
     name: php
     state: present

- name: Copying webpage to host file
  copy:
     dest: /var/www/html/webpage.php
     src: webpage.php

- name: Starting Service
  service:
     name: httpd
     state: started

